(TeX-add-style-hook
 "estabilidad"
 (lambda ()
   (LaTeX-add-labels
    "eq:lineal"
    "eq:lineal:hom"
    "eq:lineal:1"
    "eq:lineal:cons"
    "eq:jordan"
    "eq:jordan:bloque"
    "thm:estabilidad:lineal:cte"
    "table:estabilidad"
    "fig:fases:neg-pos"
    "fig:fases:neg-neg"
    "fig:fases:pos-pos"
    "fig:fases:neg-eq"
    "fig:fases:elip"
    "fig:fases:espiral:+"
    "fig:fases:espiral:-"
    "eq:3"
    "thm:lyapunov"
    "eq:cooperativo"
    "eq:hilbert"
    "eq:pendulo:estabilidad"
    "eq:pendulo:estabilidad:2"
    "thm:lyapunov:2"
    "eq:pendulo:estabilidad:3"
    "thm:lyapunov:3"
    "thm:lyapunov:5"
    "thm:chetaev"
    "eq:lyapunov"
    "eq:gradiente:1"
    "prop:gradiente:1"
    "eq:schwarz"
    "eq:gradiente:2"
    "eq:gradiente:2:s"
    "thm:lagrange-dirichlet")
   (LaTeX-add-environments
    '("ex" LaTeX-env-args ["argument"] 0)))
 :latex)

